//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHFZ_Overlay {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDamageNumbers {
            get {
                return ((bool)(this["EnableDamageNumbers"]));
            }
            set {
                this["EnableDamageNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IsRoadOverride {
            get {
                return ((int)(this["IsRoadOverride"]));
            }
            set {
                this["IsRoadOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysShowMonsterInfo {
            get {
                return ((bool)(this["AlwaysShowMonsterInfo"]));
            }
            set {
                this["AlwaysShowMonsterInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4CD60000")]
        public string Monster1BarColor {
            get {
                return ((string)(this["Monster1BarColor"]));
            }
            set {
                this["Monster1BarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4CD60000")]
        public string Monster2BarColor {
            get {
                return ((string)(this["Monster2BarColor"]));
            }
            set {
                this["Monster2BarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4CD60000")]
        public string Monster3BarColor {
            get {
                return ((string)(this["Monster3BarColor"]));
            }
            set {
                this["Monster3BarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4CD60000")]
        public string Monster4BarColor {
            get {
                return ((string)(this["Monster4BarColor"]));
            }
            set {
                this["Monster4BarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4C9000D6")]
        public string MonsterPoisonBarColor {
            get {
                return ((string)(this["MonsterPoisonBarColor"]));
            }
            set {
                this["MonsterPoisonBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4CD6A500")]
        public string MonsterBlastBarColor {
            get {
                return ((string)(this["MonsterBlastBarColor"]));
            }
            set {
                this["MonsterBlastBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4C00D1D6")]
        public string MonsterSleepBarColor {
            get {
                return ((string)(this["MonsterSleepBarColor"]));
            }
            set {
                this["MonsterSleepBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4CD4D600")]
        public string MonsterParaBarColor {
            get {
                return ((string)(this["MonsterParaBarColor"]));
            }
            set {
                this["MonsterParaBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4C777772")]
        public string MonsterStunBarColor {
            get {
                return ((string)(this["MonsterStunBarColor"]));
            }
            set {
                this["MonsterStunBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7F323232")]
        public string BackGroundColor {
            get {
                return ((string)(this["BackGroundColor"]));
            }
            set {
                this["BackGroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7F323232")]
        public string ForeGroundColor {
            get {
                return ((string)(this["ForeGroundColor"]));
            }
            set {
                this["ForeGroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7FFFFFFF")]
        public string TextColor {
            get {
                return ((string)(this["TextColor"]));
            }
            set {
                this["TextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1418")]
        public double HealthBarsX {
            get {
                return ((double)(this["HealthBarsX"]));
            }
            set {
                this["HealthBarsX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42")]
        public double HealthBarsY {
            get {
                return ((double)(this["HealthBarsY"]));
            }
            set {
                this["HealthBarsY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HealthBarsShown {
            get {
                return ((bool)(this["HealthBarsShown"]));
            }
            set {
                this["HealthBarsShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38")]
        public double PlayerInfoX {
            get {
                return ((double)(this["PlayerInfoX"]));
            }
            set {
                this["PlayerInfoX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("269")]
        public double PlayerInfoY {
            get {
                return ((double)(this["PlayerInfoY"]));
            }
            set {
                this["PlayerInfoY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayerInfoShown {
            get {
                return ((bool)(this["PlayerInfoShown"]));
            }
            set {
                this["PlayerInfoShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1589")]
        public double MonsterStatusInfoX {
            get {
                return ((double)(this["MonsterStatusInfoX"]));
            }
            set {
                this["MonsterStatusInfoX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("573")]
        public double MonsterStatusInfoY {
            get {
                return ((double)(this["MonsterStatusInfoY"]));
            }
            set {
                this["MonsterStatusInfoY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonsterStatusInfoShown {
            get {
                return ((bool)(this["MonsterStatusInfoShown"]));
            }
            set {
                this["MonsterStatusInfoShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int FontSize {
            get {
                return ((int)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
    }
}
